// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialNetwork.Data;

#nullable disable

namespace SocialNetwork.Migrations
{
    [DbContext(typeof(SocialNetworkDbContext))]
    [Migration("20250330061329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SocialNetwork.Data.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StartedAt = new DateTime(2025, 2, 24, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Project Discussion"
                        },
                        new
                        {
                            Id = 2,
                            StartedAt = new DateTime(2025, 2, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Weekend Plans"
                        },
                        new
                        {
                            Id = 3,
                            StartedAt = new DateTime(2025, 2, 23, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Meeting"
                        },
                        new
                        {
                            Id = 4,
                            StartedAt = new DateTime(2025, 1, 31, 16, 23, 0, 0, DateTimeKind.Unspecified),
                            Title = "Movie Night"
                        },
                        new
                        {
                            Id = 5,
                            StartedAt = new DateTime(2024, 8, 10, 20, 11, 0, 0, DateTimeKind.Unspecified),
                            Title = "BackUp Group"
                        },
                        new
                        {
                            Id = 6,
                            StartedAt = new DateTime(2024, 8, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Study Group"
                        });
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Friendship", b =>
                {
                    b.Property<int>("UserOneId")
                        .HasColumnType("int");

                    b.Property<int>("UserTwoId")
                        .HasColumnType("int");

                    b.HasKey("UserOneId", "UserTwoId");

                    b.HasIndex("UserTwoId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            UserOneId = 1,
                            UserTwoId = 2
                        },
                        new
                        {
                            UserOneId = 1,
                            UserTwoId = 3
                        },
                        new
                        {
                            UserOneId = 1,
                            UserTwoId = 7
                        },
                        new
                        {
                            UserOneId = 1,
                            UserTwoId = 9
                        },
                        new
                        {
                            UserOneId = 2,
                            UserTwoId = 4
                        },
                        new
                        {
                            UserOneId = 2,
                            UserTwoId = 5
                        },
                        new
                        {
                            UserOneId = 2,
                            UserTwoId = 3
                        },
                        new
                        {
                            UserOneId = 2,
                            UserTwoId = 8
                        },
                        new
                        {
                            UserOneId = 3,
                            UserTwoId = 5
                        },
                        new
                        {
                            UserOneId = 3,
                            UserTwoId = 6
                        },
                        new
                        {
                            UserOneId = 3,
                            UserTwoId = 4
                        },
                        new
                        {
                            UserOneId = 3,
                            UserTwoId = 8
                        },
                        new
                        {
                            UserOneId = 4,
                            UserTwoId = 1
                        },
                        new
                        {
                            UserOneId = 4,
                            UserTwoId = 6
                        },
                        new
                        {
                            UserOneId = 5,
                            UserTwoId = 7
                        },
                        new
                        {
                            UserOneId = 5,
                            UserTwoId = 8
                        },
                        new
                        {
                            UserOneId = 6,
                            UserTwoId = 8
                        },
                        new
                        {
                            UserOneId = 7,
                            UserTwoId = 9
                        },
                        new
                        {
                            UserOneId = 8,
                            UserTwoId = 9
                        },
                        new
                        {
                            UserOneId = 9,
                            UserTwoId = 2
                        });
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            Password = "Pass123",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            Password = "Secure456",
                            Username = "jane_doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alex_sm@mail.com",
                            Password = "TestPass789",
                            Username = "alex_smith"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sara_m@mail.com",
                            Password = "MillerPass99",
                            Username = "sara_miller"
                        },
                        new
                        {
                            Id = 5,
                            Email = "michael_b@mail.com",
                            Password = "BrownSecret88",
                            Username = "michael_brown"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emily_w@mail.com",
                            Password = "EmilyW12345",
                            Username = "emily_white"
                        },
                        new
                        {
                            Id = 7,
                            Email = "david_j@mail.com",
                            Password = "JacksonD777",
                            Username = "david_jackson"
                        },
                        new
                        {
                            Id = 8,
                            Email = "olivia_t@mail.com",
                            Password = "TaylorOlivia12",
                            Username = "olivia_taylor"
                        },
                        new
                        {
                            Id = 9,
                            Email = "william_c@mail.com",
                            Password = "ClarkWill99",
                            Username = "william_clark"
                        });
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.UserConversation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("UsersConversations");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ConversationId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 1
                        },
                        new
                        {
                            UserId = 3,
                            ConversationId = 1
                        },
                        new
                        {
                            UserId = 7,
                            ConversationId = 1
                        },
                        new
                        {
                            UserId = 9,
                            ConversationId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 2
                        },
                        new
                        {
                            UserId = 6,
                            ConversationId = 2
                        },
                        new
                        {
                            UserId = 8,
                            ConversationId = 2
                        },
                        new
                        {
                            UserId = 1,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 3,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 4,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 5,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 6,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 7,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 8,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 9,
                            ConversationId = 3
                        },
                        new
                        {
                            UserId = 1,
                            ConversationId = 4
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 4
                        },
                        new
                        {
                            UserId = 4,
                            ConversationId = 5
                        },
                        new
                        {
                            UserId = 5,
                            ConversationId = 5
                        },
                        new
                        {
                            UserId = 9,
                            ConversationId = 5
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 6
                        },
                        new
                        {
                            UserId = 4,
                            ConversationId = 6
                        },
                        new
                        {
                            UserId = 6,
                            ConversationId = 6
                        },
                        new
                        {
                            UserId = 8,
                            ConversationId = 6
                        });
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Friendship", b =>
                {
                    b.HasOne("SocialNetwork.Data.Models.User", "UserOne")
                        .WithMany()
                        .HasForeignKey("UserOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialNetwork.Data.Models.User", "UserTwo")
                        .WithMany()
                        .HasForeignKey("UserTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserOne");

                    b.Navigation("UserTwo");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Message", b =>
                {
                    b.HasOne("SocialNetwork.Data.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialNetwork.Data.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Post", b =>
                {
                    b.HasOne("SocialNetwork.Data.Models.User", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.UserConversation", b =>
                {
                    b.HasOne("SocialNetwork.Data.Models.Conversation", "Conversation")
                        .WithMany("UsersConversations")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialNetwork.Data.Models.User", "User")
                        .WithMany("UsersConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UsersConversations");
                });

            modelBuilder.Entity("SocialNetwork.Data.Models.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Posts");

                    b.Navigation("UsersConversations");
                });
#pragma warning restore 612, 618
        }
    }
}
